name: tests

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [oldstable, stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v -covermode=atomic -coverprofile=coverage.txt ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest' && matrix.go-version == 'stable'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
